version: '3'
services:
  mlflow-server:
    build: .\server\docker
    image: mlflow-server:v0.1
    container_name: mlflow-server
    tty: true
    restart: always
    ports:
      - 8000:5000
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.2
    volumes:
      - E:\projects\mlflow-sample\server:/app/mlflow-sample/server
  training-server:
    build: .\model\docker
    image: mlflow-training:v0.1
    container_name: mlflow-training
    tty: true
    restart: always
    ports:
      - 9000:5000
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.3
    volumes:
      - E:\projects\mlflow-sample\model:/app/mlflow-sample/model
      - E:\dataset:/dataset
networks:
  mlflow-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
