version: '3'
services:
  mlflow-server:
    build: .\server\docker
    image: mlflow-server:v0.1
    container_name: mlflow-server
    tty: true
    restart: always
    ports:
      - 8000:5000
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.2
    volumes:
      - E:\projects\mlflow-sample\server:/app/mlflow-sample/server
  training-server:
    build: .\model\docker
    image: mlflow-training:v0.1
    container_name: mlflow-training
    tty: true
    restart: always
    ports:
      - 9000:5000
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.3
    volumes:
      - E:\projects\mlflow-sample\model:/app/mlflow-sample/model
      - E:\dataset:/dataset
  adminer:
    image: adminer
    container_name: mlflow-adminer
    restart: always
    depends_on:
      - database-server
    ports: 
      - "8080:8080"
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.4
  database-server:
    image: mysql:5.7
    container_name: ${DB_HOST}
    platform: 'linux/amd64'
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.5
    volumes:
      - E:\projects\mlflow-sample\database:/var/lib/mysql
networks:
  mlflow-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
