version: '3'
services:
  mlflow-server:
    build: .\server\docker
    image: mlflow-server:v0.1
    container_name: mlflow-server
    tty: true
    restart: always
    depends_on:
      - database-server
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DB_HOST}:3306/${DB_NAME}
      --default-artifact-root ftp://${FTP_USER}:${FTP_PASSWORD}@172.30.0.6:21/home/ftpusers
    ports:
      - 8000:5000
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.2
    volumes:
      - E:\projects\mlflow-sample\server:/server
  training-server:
    build: .\model\docker
    image: mlflow-training:v0.1
    container_name: mlflow-training
    tty: true
    restart: always
    ports:
      - 9000:5000
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.3
    volumes:
      - E:\projects\mlflow-sample\model:/app/mlflow-sample/model
      - E:\dataset:/dataset
  adminer:
    image: adminer
    container_name: mlflow-adminer
    restart: always
    depends_on:
      - database-server
    ports: 
      - "8080:8080"
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.4
  database-server:
    image: mysql:5.7
    container_name: ${DB_HOST}
    platform: 'linux/amd64'
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.5
    volumes:
      - E:\projects\mlflow-sample\database:/var/lib/mysql
  ftp-server:
    image: stilliard/pure-ftpd:latest
    container_name: mlflow-ftp-server
    restart: always
    environment:
      - PUBLICHOST=localhost
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_USER_HOME=/home/ftpusers
      - ADDED_FLAGS="--tls=2"
    ports:
      - 21:21
      - 30000-30009:30000-30009
    networks:
      mlflow-net:
        ipv4_address: 172.30.0.6
    volumes:
      - E:\projects\mlflow-sample\artifacts:/home/ftpusers
networks:
  mlflow-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
